### ISSUE TITLE
Intermediate Fusion Model Config Issues with KITTI and ScanNet

### ISSUE THREAD

**Issue by altaykacan** [drprojects/DeepViewAgg#19]
Hello @drprojects ,

Sorry for bothering you with questions during the holiday season but I'm really puzzled about this one.

I was trying to configure a default model provided (`small_2d_3d`) to implement intermediate fusion as described in your nice paper but encountered cryptic CUDA errors in the backward pass while training on the KITTI360 dataset. What I was aiming to do was to fuse the image features only at the last encoder layer but anytime I change the `branching_index` to a higher value I get the same error.

Here's a config that works in my environment:
```
base-intermediate:
    class: sparseconv3d.APIModel
    conv_type: "SPARSE"
    backend: "torchsparse"
    backbone: # backbone offset specific for Sparse conv application builder
        define_constants:
            in_feat: 2
            block: ResBlock # Can be any of the blocks in modules/MinkowskiEngine/api_modules.py
            out_feat_img_0: 128  # out dim of CityscapesResNet18

        down_conv:
            module_name: ResNetDown
            block: block
            conv3d_after_fusion: False # conv->fusion
            N: [ 0, 1, 1, 1, 1 ]
            kernel_size: [ 3, 2, 2, 2, 2 ]
            stride: [ 1, 2, 2, 2, 2 ]

            down_conv_nn:
              [
                  [ FEAT, 4*in_feat ],
                  [ 4*in_feat + out_feat_img_0, in_feat ],
                  [ in_feat , 2*in_feat ],
                  [ 2*in_feat , 4*in_feat ],
                  [ 4*in_feat, 8*in_feat ],
              ]

            image:
                down_conv:
                    module_name: CityscapesResNet18TruncatedLayer0
                atomic_pooling:
                    module_name: BimodalCSRPool
                    mode: max
                view_pooling:
                    module_name: BimodalCSRPool
                    mode: max
                fusion:
                    module_name: BimodalFusion
                    mode: concatenation
                branching_index: 1
                out_channels: 4*in_feat + out_feat_img_0  # This is necessary to support batches with no images
#                 checkpointing: cav

        up_conv:
            block: block
            module_name: ResNetUp
            N: [ 1, 1, 1, 1, 1 ]
            kernel_size: [ 2, 2, 2, 2, 3 ]
            stride: [ 2, 2, 2, 2, 1 ]
            up_conv_nn:
                [
                  [ 8*in_feat, 4*in_feat, 4*in_feat ],
                  [ 4*in_feat, 2*in_feat, 4*in_feat ],
                  [ 4*in_feat, in_feat, 3*in_feat ],
                  [ 3*in_feat, 4*in_feat + out_feat_img_0, 3*in_feat ],
                  [ 3*in_feat, 0, 3*in_feat ],
                ]
```

And if I change the branching index by even 1 (i.e. the config below) I get the following error which contains some comments I added while trying to debug, hopefully it isn't distracting!

The error is: 
```
The model will not be able to be used from pretrained weights without the corresponding dataset. Current properties are {'feature_dimension': 1, 'num_classes': 15}
  0%|                                                                                                                                                                                                                            | 0/6000 [00:00<?, ?it/s]/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [395,0,0], thread: [48,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [5,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [6,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [7,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [8,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [9,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [10,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [11,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [12,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [399,0,0], thread: [13,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
  0%|                                                                                                                                                                                                                            | 0/6000 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/home/rozenberszki/altay/DeepViewAgg_playground/debug_kitti_train.py", line 107, in <module>
    main(cfg)
  File "/home/rozenberszki/anaconda3/envs/dva/lib/python3.7/site-packages/hydra/main.py", line 44, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/rozenberszki/altay/DeepViewAgg_playground/debug_kitti_train.py", line 41, in main
    trainer.train()
  File "/home/rozenberszki/altay/DeepViewAgg_playground/torch_points3d/trainer.py", line 146, in train
    self._train_epoch(epoch)
  File "/home/rozenberszki/altay/DeepViewAgg_playground/torch_points3d/trainer.py", line 202, in _train_epoch
    self._model.optimize_parameters(epoch, self._dataset.batch_size)
  File "/home/rozenberszki/altay/DeepViewAgg_playground/torch_points3d/models/base_model.py", line 249, in optimize_parameters
    self.backward()  # calculate gradients
  File "/home/rozenberszki/altay/DeepViewAgg_playground/torch_points3d/models/segmentation/sparseconv3d.py", line 58, in backward
    self.loss_seg.backward() # TODO: WITH KITTI THIS IS SOMEHOW EMPTY, do loss.item()
  File "/home/rozenberszki/anaconda3/envs/dva/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/rozenberszki/anaconda3/envs/dva/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered

```
And this is the model I ran it with:

```
base-intermediate:
    class: sparseconv3d.APIModel
    conv_type: "SPARSE"
    backend: "torchsparse"
    backbone: # backbone offset specific for Sparse conv application builder
        define_constants:
            in_feat: 2
            block: ResBlock # Can be any of the blocks in modules/MinkowskiEngine/api_modules.py
            out_feat_img_0: 128  # out dim of CityscapesResNet18

        down_conv:
            module_name: ResNetDown
            block: block
            conv3d_after_fusion: False # conv->fusion

            N: [ 0, 1, 1, 1, 1 ]
            kernel_size: [ 3, 2, 2, 2, 2 ]
            stride: [ 1, 2, 2, 2, 2 ]

            down_conv_nn:
              [
                  [ FEAT, 4*in_feat ],
                  [ 4*in_feat, in_feat ],
                  [ in_feat + out_feat_img_0 , 2*in_feat ], # <== Changed this
                  [ 2*in_feat , 4*in_feat ],
                  [ 4*in_feat, 8*in_feat ],
              ]

            image:
                down_conv:
                    module_name: CityscapesResNet18TruncatedLayer0
                atomic_pooling:
                    module_name: BimodalCSRPool
                    mode: max
                view_pooling:
                    module_name: BimodalCSRPool
                    mode: max
                fusion:
                    module_name: BimodalFusion
                    mode: concatenation
                branching_index: 2                      # <== Changed this
                out_channels: in_feat + out_feat_img_0  # <== Changed this
#                 checkpointing: cav

        up_conv:
            block: block
            module_name: ResNetUp
            N: [ 1, 1, 1, 1, 1 ]
            kernel_size: [ 2, 2, 2, 2, 3 ]
            stride: [ 2, 2, 2, 2, 1 ]
            up_conv_nn:
                [
                  [ 8*in_feat, 4*in_feat, 4*in_feat ],
                  [ 4*in_feat, 2*in_feat, 4*in_feat ],
                  [ 4*in_feat, in_feat + out_feat_img_0, 3*in_feat ], # <== Changed this
                  [ 3*in_feat, 4*in_feat, 3*in_feat ],
                  [ 3*in_feat, 0, 3*in_feat ],
                ]
```

What I'd like to be able to do is to set the branching index to 5 and concatenate the image features to the 3d features right before the decoder. The reason the branching index is 1 in the first model is that as far as I understand `n_early_conv` is by default equal to 1. Me and a teammate are looking into an alternative fusion strategy which would only make sense in the intermediate fusion case. Hopefully we can share our results with you once we get everything running!

- Could you please let me know what might be causing this problem or whether something is wrong in the way the config is specified?
- Also I couldn't find any premade configs for the intermediate fusion case, did I miss them? Could you please point me in the right direction so I could use those as examples?

Thank you in advance for your help and I hope you had a nice holiday season with your loved ones!

EDIT: Added context to the error message

**Comment by drprojects** [comment]
Hi @altaykacan 

Sorry for the late reply, I was not available for a while. I will investigate this issue and get back to you as soon as I find the reason for this error.

**Comment by drprojects** [comment]
Hi @altaykacan,

Thanks for using this project and sharing this bug, there was indeed something I needed to fix.

You are correct in trying to change the branching index parameter to reach your goal. And as you correctly pointed out, for multimodal models, `n_early_conv=1` by default, to allow for early injection of 2D features before any 3D conv.

There are indeed model configs similar to what you want to do for S3DIS. Those are named `XYZ-RGB-L4-LX`, meaning fusing the ouptut of the 2D encoder layer 4 into the `X'th` 3D encoder layer.

Note that those model configs have a slightly different way of declaring the convs due to `conv3d_after_fusion=True`, to allow 3D convs before and after the fusion operation on the points of a given encoder stage. If you need to concatenate the 2D features with the 3D features right before the 3D decoder, without applying any 3D conv on them, you should be able to set `conv3d_after_fusion=False`. In this regard, your `base-intermediate` config seems correct to me.

I investigated the issue you had encountered. I found a discrepancy in the mappings occasionally appeared when both the images and the point clouds were downsampled, which typically happens in intermediate fusion. A more recent modification in the project had broken the normal behavior. Long story short: I fixed it, you can pull the latest commit, and should be able to succesfully run your `base-intermediate` as well as my `XYZ-RGB-L4-LX` models.

One remark regarding your `base-intermediate` model: I don't know if it was meant for debugging only but your `in_feat=2` seems a bit small to me. You might want to increase it if you need to capture complex 3D structures.

**Comment by altaykacan** [comment]
Thank you so much for looking into it and fixing the bug! Also, thank you for clarifying the naming of the models and the hint regarding the `in_feat=2`, this was just a small model I was using for debugging and I'll keep your hint in mind.
